export const ActionTypes = {
    GET_LOCATION: "GET_LOCATION",
    SELECCTED_USER: "SELECCTED_USER",
    GET_SELECTED_LOCATION_ID: "GET_SELECTED_LOCATION_ID", 
    GET_CATEGORY: "GET_CATEGORY", 
    GET_PLAN_CATEGORY: "GET_PLAN_CATEGORY", 
    GET_SIDEBAR: "GET_SIDEBAR", 
    GET_DOCUMENT: "GET_DOCUMENT", 
    GET_PLAN: "GET_PLAN", 
}